module.exports={
    mascotas:[
        {tipo:"Perro",nombre:"David0",dueno:"Camilo"},
        {tipo:"Perro",nombre:"David1",dueno:"Camilo"},
        {tipo:"Perro",nombre:"David2",dueno:"Camilo"},
        {tipo:"Perro",nombre:"David3",dueno:"Camilo"},
    ],
    veterinarias:[
        {nombre:"Alexandra",apellido:"perez",documento:"12344567"},
        {nombre:"Alexandrer",apellido:"Gómez",documento:"424233"},
        {nombre:"Julián",apellido:"López",documento:"78445562"},
        {nombre:"Tatiana",apellido:"Maldonado",documento:"3214845562"},
    ],
    duenos:[
        {nombre:"Andrea",apellido:"perez",documento:"44567"},
        {nombre:"Ana",apellido:"Cardona",documento:"52433"},
        {nombre:"Mateo",apellido:"Mendoza",documento:"645562"},
        {nombre:"Mauricio",apellido:"Maradona",documento:"821562"},
    ],
    consultas:[
        {
            mascota:0,
            veterinaria:0,
            fechaCreacion:new Date(),
            fechaEdicion:new Date(),
            historia:'',
            diagnostico:'',
        }
    ],
}; 
